site_name: fakemap

site_url: https://MattAGUT.github.io/fakemap

repo_url: https://github.com/MattAGUT/fakemap

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          execute: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/MattAGUT/fakemap/issues
    - Examples: 
           - examples/intro.ipynb
           - examples/folium.ipynb
           - examples/ipyleaflet.ipynb
           - examples/fakemap.ipynb
           - examples/ipyleafletmappingLab7.ipynb
           - examples/FoliumMappingLab7.ipynb
           - examples/AddingImages.ipynb
           - examples/raster.ipynb
           - examples/Lab9Adddropdown.ipynb
           - examples/MapingGeoTIFFS.ipynb
           - examples/MetadataGeoTIFF.ipynb
           - examples/SpectralProfiles.ipynb
           - examples/ExamplesforRealWorldApplication.ipynb
           - examples/MoreRealWorldExamples.ipynb
           - examples/finalexamexamples.ipynb
    - API Reference:
          - fakemap module: fakemap.md
          - foliummap module: foliummap.md
